// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsEFSample.DataAccess;

namespace WinFormsEFSample.Migrations
{
    [DbContext(typeof(HerbDbContext))]
    [Migration("20211015074153_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WinFormsEFSample.DataAccess.Models.Herb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Herb");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6b2ae7f-82f4-4099-86a9-556a62338271"),
                            Name = "Anis"
                        });
                });

            modelBuilder.Entity("WinFormsEFSample.DataAccess.Models.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HerbId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("To")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HerbId");

                    b.ToTable("Season");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e358d618-d376-439a-9cd3-5e2c02849103"),
                            From = "September",
                            HerbId = new Guid("d6b2ae7f-82f4-4099-86a9-556a62338271"),
                            To = "November"
                        });
                });

            modelBuilder.Entity("WinFormsEFSample.DataAccess.Models.Season", b =>
                {
                    b.HasOne("WinFormsEFSample.DataAccess.Models.Herb", "Herb")
                        .WithMany("Seasons")
                        .HasForeignKey("HerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herb");
                });

            modelBuilder.Entity("WinFormsEFSample.DataAccess.Models.Herb", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
