// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsEFSample.DataAccess;

namespace WinFormsEFSample.Migrations
{
    [DbContext(typeof(HerbDbContext))]
    [Migration("20211015091227_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WinFormsEFSample.DataAccess.Models.Herb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Herb");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7660f77-9962-45ee-a601-cfa7799aa85e"),
                            Name = "Anis"
                        },
                        new
                        {
                            Id = new Guid("32f2a89a-d70d-4ebe-8ed5-69dab23501c8"),
                            Name = "Basilikum"
                        },
                        new
                        {
                            Id = new Guid("1977d469-ef12-464c-bee6-03fc42ea1849"),
                            Name = "Bockshornklee"
                        },
                        new
                        {
                            Id = new Guid("2b87619d-e0c6-4271-8a53-537e95c05d7e"),
                            Name = "Borretsch"
                        },
                        new
                        {
                            Id = new Guid("c8d2c2e3-9fa0-4a85-a279-1d2e019b6cb0"),
                            Name = "Bärlauch"
                        },
                        new
                        {
                            Id = new Guid("4236f6f6-bb89-4952-a60e-69bf87f461ab"),
                            Name = "Dill"
                        },
                        new
                        {
                            Id = new Guid("a821d32e-0d32-4e94-bb0a-75568764bf15"),
                            Name = "Estragon"
                        },
                        new
                        {
                            Id = new Guid("00579af1-2d77-4c4a-96fe-570ef0455cfe"),
                            Name = "Kerbel"
                        },
                        new
                        {
                            Id = new Guid("0a5923c6-266c-4478-972d-4a8df335d658"),
                            Name = "Knoblauch"
                        },
                        new
                        {
                            Id = new Guid("4858c0fb-8a43-4b61-858c-9eb684bfbda5"),
                            Name = "Kresse"
                        },
                        new
                        {
                            Id = new Guid("16c08968-1869-439a-a403-4f9757b96594"),
                            Name = "Kümmel"
                        },
                        new
                        {
                            Id = new Guid("f5af8933-3f28-4d0c-be9f-7c86743d25a0"),
                            Name = "Minze"
                        },
                        new
                        {
                            Id = new Guid("2587bd92-a90e-450b-9e78-bf0231a046dc"),
                            Name = "Oregano"
                        },
                        new
                        {
                            Id = new Guid("95d6e787-81a6-435c-a6a9-2aea905ec3d3"),
                            Name = "Petersilie"
                        },
                        new
                        {
                            Id = new Guid("a6af90e8-c94d-4d55-86e7-0e3d523aa83d"),
                            Name = "Salbei"
                        },
                        new
                        {
                            Id = new Guid("0a728168-51a5-4ad7-ac8c-876afce21b78"),
                            Name = "Schnittlauch"
                        },
                        new
                        {
                            Id = new Guid("8fc4ae53-ec57-45a5-9788-daf495bd3111"),
                            Name = "Thymian"
                        },
                        new
                        {
                            Id = new Guid("0d6e5dd3-e41d-4cd5-a639-7c0a9d69549d"),
                            Name = "Wurzelpetersilie"
                        },
                        new
                        {
                            Id = new Guid("95010393-342e-4c36-90d0-8d5c9d0c13dc"),
                            Name = "Zitronenmelisse"
                        });
                });

            modelBuilder.Entity("WinFormsEFSample.DataAccess.Models.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HerbId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("To")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HerbId");

                    b.ToTable("Season");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8af96254-d025-4f5c-a56c-9b4cef659ca6"),
                            From = "September",
                            HerbId = new Guid("c7660f77-9962-45ee-a601-cfa7799aa85e"),
                            To = "November"
                        },
                        new
                        {
                            Id = new Guid("00b2619f-9536-4ce0-9e63-780c95f3bce5"),
                            From = "Juni",
                            HerbId = new Guid("32f2a89a-d70d-4ebe-8ed5-69dab23501c8"),
                            To = "September"
                        },
                        new
                        {
                            Id = new Guid("0d3993d4-3848-4bdf-86dc-571dad3698bc"),
                            From = "August",
                            HerbId = new Guid("1977d469-ef12-464c-bee6-03fc42ea1849"),
                            To = "September"
                        },
                        new
                        {
                            Id = new Guid("d1b60b24-0a69-4848-afcc-a8336e0c018c"),
                            From = "Juni",
                            HerbId = new Guid("2b87619d-e0c6-4271-8a53-537e95c05d7e"),
                            To = "August"
                        },
                        new
                        {
                            Id = new Guid("0c60496a-80dc-422c-8a93-3555c94634fa"),
                            From = "März",
                            HerbId = new Guid("c8d2c2e3-9fa0-4a85-a279-1d2e019b6cb0"),
                            To = "Juni"
                        },
                        new
                        {
                            Id = new Guid("6b99a058-93d3-47da-a5f0-2a614d253754"),
                            From = "April",
                            HerbId = new Guid("4236f6f6-bb89-4952-a60e-69bf87f461ab"),
                            To = "September"
                        },
                        new
                        {
                            Id = new Guid("06b9c5a0-d6d9-40f5-b4b5-bf4eba20986a"),
                            From = "Mai",
                            HerbId = new Guid("a821d32e-0d32-4e94-bb0a-75568764bf15"),
                            To = "Oktober"
                        },
                        new
                        {
                            Id = new Guid("3b2c6149-86ee-4444-b9b2-bb903515788d"),
                            From = "April",
                            HerbId = new Guid("00579af1-2d77-4c4a-96fe-570ef0455cfe"),
                            To = "Oktober"
                        },
                        new
                        {
                            Id = new Guid("4ef6e92a-5165-4197-8ab3-3dfaaa056c1a"),
                            From = "Juni",
                            HerbId = new Guid("0a5923c6-266c-4478-972d-4a8df335d658"),
                            To = "August"
                        },
                        new
                        {
                            Id = new Guid("c72ea7b9-e4c6-4a83-b1f1-22fccf8074df"),
                            From = "Januar",
                            HerbId = new Guid("4858c0fb-8a43-4b61-858c-9eb684bfbda5"),
                            To = "Dezember"
                        },
                        new
                        {
                            Id = new Guid("2e44a90e-2a59-47b3-b071-1e45e18512f8"),
                            From = "Mai",
                            HerbId = new Guid("16c08968-1869-439a-a403-4f9757b96594"),
                            To = "Mai"
                        },
                        new
                        {
                            Id = new Guid("0ef4791a-db80-4c47-8c9b-083dffddc014"),
                            From = "August",
                            HerbId = new Guid("16c08968-1869-439a-a403-4f9757b96594"),
                            To = "Oktober"
                        },
                        new
                        {
                            Id = new Guid("4e7015ae-1e7e-4393-a1c9-ed94d0afc3a0"),
                            From = "Mai",
                            HerbId = new Guid("f5af8933-3f28-4d0c-be9f-7c86743d25a0"),
                            To = "September"
                        },
                        new
                        {
                            Id = new Guid("becc6315-8d28-43da-a16b-90925a460e13"),
                            From = "April",
                            HerbId = new Guid("2587bd92-a90e-450b-9e78-bf0231a046dc"),
                            To = "Oktober"
                        },
                        new
                        {
                            Id = new Guid("341e37b3-6fd4-4db2-96f3-8d90e861f4a2"),
                            From = "April",
                            HerbId = new Guid("95d6e787-81a6-435c-a6a9-2aea905ec3d3"),
                            To = "Oktober"
                        },
                        new
                        {
                            Id = new Guid("1118ee13-7d7b-4fcc-85b5-caaea124daad"),
                            From = "April",
                            HerbId = new Guid("a6af90e8-c94d-4d55-86e7-0e3d523aa83d"),
                            To = "November"
                        },
                        new
                        {
                            Id = new Guid("f4db0e30-ac74-44ce-9dbd-235675c94559"),
                            From = "April",
                            HerbId = new Guid("0a728168-51a5-4ad7-ac8c-876afce21b78"),
                            To = "Oktober"
                        },
                        new
                        {
                            Id = new Guid("c9276dfd-ac0a-4a95-a3c1-dad38f38d3aa"),
                            From = "März",
                            HerbId = new Guid("8fc4ae53-ec57-45a5-9788-daf495bd3111"),
                            To = "Oktober"
                        },
                        new
                        {
                            Id = new Guid("28a1fd0c-1ad5-4045-aa3d-73dc96235a83"),
                            From = "Januar",
                            HerbId = new Guid("0d6e5dd3-e41d-4cd5-a639-7c0a9d69549d"),
                            To = "April"
                        },
                        new
                        {
                            Id = new Guid("0623177e-602b-4855-90ca-34b262c343c5"),
                            From = "Oktober",
                            HerbId = new Guid("0d6e5dd3-e41d-4cd5-a639-7c0a9d69549d"),
                            To = "Dezember"
                        },
                        new
                        {
                            Id = new Guid("b5a6f36a-27cb-4053-9472-8f781821d4e8"),
                            From = "April",
                            HerbId = new Guid("95010393-342e-4c36-90d0-8d5c9d0c13dc"),
                            To = "Oktober"
                        });
                });

            modelBuilder.Entity("WinFormsEFSample.DataAccess.Models.Season", b =>
                {
                    b.HasOne("WinFormsEFSample.DataAccess.Models.Herb", "Herb")
                        .WithMany("Seasons")
                        .HasForeignKey("HerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herb");
                });

            modelBuilder.Entity("WinFormsEFSample.DataAccess.Models.Herb", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
